const LEVELS = [
  { id: 'A1', name: 'Beginner', desc: 'مبتدئ - أساسيات اللغة', color: '#4CAF50', icon: '🌱' },
  { id: 'A2', name: 'Elementary', desc: 'ابتدائي - تكوين الجمل', color: '#8BC34A', icon: '🌿' },
  { id: 'B1', name: 'Intermediate', desc: 'متوسط - محادثات يومية', color: '#FFC107', icon: '🌳' },
  { id: 'B2', name: 'Upper Intermediate', desc: 'متوسط متقدم - نقاش معمق', color: '#FF9800', icon: '🔥' },
  { id: 'C1', name: 'Advanced', desc: 'متقدم - طلاقة', color: '#F44336', icon: '⚡' },
  { id: 'C2', name: 'Proficient', desc: 'خبير - إتقان تام', color: '#9C27B0', icon: '👑' }
];

const TOPICS = {
  A1: [
    'My Morning Routine','My Family','My Favorite Food','My House','At the Supermarket',
    'My Pet Dog','The Weather Today','Going to School','My Hobbies','My Clothes'
  ],
  A2: [
    'A Day at the Beach','My Best Friend','A Visit to the Doctor','My City','My Birthday Party',
    'My Favorite Book','Cooking with Mom','A Letter to a Pen Pal','The Lost Kitten','My Dream Job'
  ],
  B1: [
    'Learning from Mistakes','Technology in Our Lives','Healthy Lifestyle','Traveling to a New Country','Environmental Awareness',
    'The Importance of Education','Social Media','Volunteering','Cultural Festivals','Overcoming Challenges'
  ],
  B2: [
    'The Impact of Globalization','Artificial Intelligence','Mental Health Awareness','Space Exploration','Renewable Energy',
    'Cultural Diversity','The Gig Economy','Media Literacy','Sustainable Living','Higher Education Debate'
  ],
  C1: [
    'The Paradox of Choice','The Neuroscience of Learning','Cryptocurrency and Blockchain','The Ethics of Genetic Engineering','The Psychology of Social Media',
    'The Future of Work','Conscious Consumerism','The Art of Negotiation','Urban Sustainability','The Science of Happiness'
  ],
  C2: [
    'Epistemology in the Digital Age','Quantum Computing','The Phenomenology of Time','Geopolitics of Energy','Consciousness and the Brain',
    'Existentialism in Modern Life','Post-Truth Society','The Economics of Inequality','Artificial General Intelligence','The Meaning of Life'
  ]
};

const STORIES = {
  A1: [
    `Every morning, I wake up at 7 o'clock. I brush my teeth and wash my face. Then I eat breakfast. I usually eat bread and drink milk. After breakfast, I go to school. I study English and Math. I like my teachers. In the afternoon, I go home. I do my homework and play with my friends. At night, I eat dinner with my family. I watch TV and then I go to bed at 10 o'clock.`,
    `I have a small family. My father is a doctor. My mother is a teacher. I have one brother and one sister. My brother is 10 years old. My sister is 15 years old. We live in a house near the school. On weekends, we visit my grandparents. My grandfather tells stories. My grandmother makes cake. I love my family very much.`,
    `I like many kinds of food. My favorite food is pizza. It has cheese and tomatoes. I also like pasta and rice. For breakfast, I eat cereal with milk. For lunch, I eat sandwiches. I drink water and juice. I do not like coffee because it is bitter. My mother cooks delicious food. I help her in the kitchen sometimes.`,
    `I live in a small house. It has four rooms: a living room, a kitchen, two bedrooms, and a bathroom. My bedroom is blue. I have a bed, a desk, and a chair. The living room is big. We watch TV there. The kitchen is next to the living room. My mother cooks there. There is a garden in front of the house. I play there with my dog.`,
    `Today I go to the supermarket with my mother. We buy many things. We get apples, bananas, and oranges. We also buy milk, bread, and eggs. The supermarket is big and busy. I see many people. My mother pays at the cashier. Then we go home. I carry the bags. I am happy because we have food for the week.`,
    `I have a pet dog. His name is Max. He is brown and white. He has big eyes and a long tail. Max is two years old. He likes to play in the garden. I throw the ball and he runs to get it. He eats dog food and drinks water. At night, he sleeps in his bed. Max is my best friend. I love him very much.`,
    `Today is a sunny day. The sky is blue. It is hot outside. I wear a t-shirt and shorts. In summer, it is very hot. I go to the beach with my family. In winter, it is cold. I wear a jacket and a hat. I like spring because the flowers are beautiful. The weather is nice in spring. It is not too hot and not too cold.`,
    `I go to school from Sunday to Thursday. School starts at 8 o'clock. I study many subjects. I like English and Science. My English teacher is nice. She helps me learn new words. At break time, I play with my friends. We eat snacks and talk. School finishes at 2 o'clock. I take the bus home. I like school because I learn new things.`,
    `In my free time, I like to draw. I draw animals and flowers. I also like reading books. My favorite book is about a magic tree. I read before I sleep. Sometimes I ride my bike in the park. I play football with my friends on Friday. Watching cartoons is fun too. I like free time because I can do what I love.`,
    `Today I wear a blue shirt and black pants. I have new shoes. They are white and red. My mother buys my clothes from the mall. I like wearing comfortable clothes. In summer, I wear shorts and t-shirts. In winter, I wear sweaters and jackets. My favorite color is blue. I have many blue clothes. I also like wearing hats.`
  ],
  A2: [
    `Last weekend, my family and I went to the beach. The weather was hot and sunny. We took a big umbrella and a blanket. My brother played in the water. I built a big sandcastle with my sister. My mother prepared sandwiches and juice for lunch. We stayed at the beach for four hours. In the evening, we watched the sunset. It was beautiful. We took many photos. I felt very happy. I want to go to the beach again next weekend.`,
    `My best friend's name is Ahmed. He is 12 years old. We sit together in class. Ahmed is very funny. He makes me laugh every day. After school, we play football together. Sometimes we go to the park near our houses. On weekends, we play video games. Ahmed is kind and helpful. When I need help with homework, he helps me. I am lucky to have a friend like him.`,
    `Yesterday, I felt sick. I had a headache and a fever. My mother took me to the doctor. The clinic was near our house. We waited for 15 minutes. The doctor was kind. He checked my temperature. It was 38 degrees. He gave me medicine. He said, "Drink a lot of water and rest for two days." I stayed at home. I drank warm soup and slept a lot. Today I feel much better.`,
    `I live in a small city. There is a big market in the center. You can buy fruits, vegetables, and clothes there. There is also a library. I go there to read books. My favorite place is the park. It has big trees and a lake. There are ducks in the lake. There is a hospital near my school. There are many shops and restaurants. I like my city because it is clean and beautiful.`,
    `Last week was my birthday. I turned 11 years old. We had a party at home. My mother decorated the house with balloons. My father bought a big chocolate cake. My friends came to the party. We played games and danced. My friend Sara gave me a drawing book. My friend Omar gave me a football. We ate pizza and cake. I blew out the candles and made a wish. It was the best birthday ever.`,
    `My favorite book is "The Secret Garden". It is about a girl named Mary. She finds a secret garden in her uncle's house. The garden is old and empty. Mary takes care of it. She plants flowers and makes the garden beautiful again. She makes new friends too. The book teaches us about nature and friendship. I read this book three times. I love stories about nature and adventure.`,
    `Yesterday, I helped my mother cook dinner. We made pasta with tomato sauce. First, we boiled water in a big pot. Then we put the pasta in the water. My mother cut vegetables: onions, peppers, and tomatoes. I stirred the sauce. It smelled delicious. After 20 minutes, the pasta was ready. We put the sauce on top. We ate together as a family. I felt proud because I helped make the dinner.`,
    `Dear Emma, My name is Ali. I am 11 years old. I live in Saudi Arabia with my family. I have two brothers and one sister. I like playing football and reading books. My favorite subject is English. I want to learn more languages. What do you like to do? How many people are in your family? Please write back. I want to know about your country. Best wishes, Ali.`,
    `Last Tuesday, I found a small kitten in my garden. It was white and gray. It looked scared and hungry. I gave it some milk and food. The kitten ate quickly. I looked around for its mother, but I did not see her. I took the kitten inside my house. My mother said we can keep it if nobody comes for it. I put a box with a soft towel for the kitten to sleep. I named it Snowy. Now Snowy lives with us and I take care of her every day.`,
    `When I grow up, I want to be a teacher. I want to help children learn new things. I will teach English or Science. I will be a kind teacher like my teacher Miss Sara. She makes learning fun. I will prepare fun activities for my students. I will help them read and write. Being a teacher is a great job because you help people every day.`
  ],
  B1: [
    `Last year, I failed my math exam. I felt very disappointed because I had studied for only one day. I realized that I needed to change my study habits. I started studying a little bit every day instead of waiting until the last minute. I also asked my teacher for extra help. She gave me useful tips. I practiced more problems and reviewed my notes regularly. This year, I got an A on my math exam. I learned that hard work and consistency are more important than talent.`,
    `Technology has changed the way we live. Smartphones help us communicate with people anywhere in the world. We can send messages, make video calls, and share photos instantly. The internet gives us access to information about any topic. I use my phone to learn English through apps and websites. However, technology also has disadvantages. Many people spend too much time on their phones and ignore real-life conversations. I try to balance my screen time with outdoor activities.`,
    `Staying healthy is very important. I try to eat a balanced diet with fruits, vegetables, and protein. I avoid sugary drinks and fast food because they are unhealthy. I exercise three times a week. I run in the park and do push-ups at home. Drinking enough water is also essential. I drink eight glasses of water every day. Sleep is another important factor. I sleep for eight hours every night. Good habits help me feel energetic and focused at school.`,
    `Last summer, my family traveled to Turkey. It was my first time traveling abroad. We visited Istanbul, a city that connects Europe and Asia. We saw the Blue Mosque and Hagia Sophia. The architecture was amazing. We tried local food like kebabs and baklava. The Turkish people were friendly and helpful. I practiced my English with tourists from other countries. I learned that traveling opens your mind and helps you understand different cultures.`,
    `Our planet is facing serious problems like pollution and climate change. Factories and cars produce harmful gases that damage the environment. I try to help the environment in small ways. I recycle paper, plastic, and glass at home. I turn off lights when I leave a room to save electricity. I use a reusable water bottle instead of plastic ones. My school has a recycling program too. If everyone does their part, we can make a big difference.`,
    `Education is the key to success. It gives us knowledge and skills to build a better future. In many parts of the world, children do not have access to education. They cannot go to school because of poverty or conflict. I feel grateful that I can go to school every day. Education helps us understand the world and make good decisions. It also opens doors to better job opportunities. I believe everyone deserves the chance to learn and grow.`,
    `Social media platforms like Instagram, Twitter, and TikTok are very popular. People use them to share photos, news, and opinions. I use social media to connect with my friends and follow pages that teach English. However, social media also has negative effects. Some people spend hours scrolling and waste time. Cyberbullying is another problem. Fake news spreads quickly too. I think we should use social media wisely and limit our screen time.`,
    `Last month, I volunteered at a local charity. We organized a food drive for families in need. I helped collect donations and pack food boxes. We delivered the boxes to people who could not afford to buy food. Seeing their smiles made me feel warm inside. Volunteering teaches us empathy and gratitude. It also brings the community together. I plan to volunteer regularly. Even small acts of kindness can make a big difference.`,
    `Cultural festivals are celebrations that bring people together. In my country, we have a festival called Janadriyah. It shows our heritage through music, dance, and food. There are traditional dances like Ardah. People wear traditional clothes and ride camels. Visitors can try local foods like Kabsa and dates. I love this festival because it teaches young people about their culture. Festivals help keep traditions alive.`,
    `Last year, I had a fear of public speaking. Whenever I had to present in class, my heart would race and I would forget my words. My teacher noticed and gave me advice. She said preparation and practice are the keys to confidence. I started practicing in front of a mirror. Then I presented to my family. Gradually, I became more comfortable. Last week, I gave a presentation in front of the whole class. I spoke clearly and confidently. Overcoming this challenge taught me that facing your fears is the only way to grow.`
  ],
  B2: [
    `Globalization has transformed the world into a connected village. International trade, technology, and travel have brought countries closer than ever before. People can buy products from anywhere in the world. Companies operate across multiple continents. However, globalization also has drawbacks. Local cultures may be eroded by dominant global influences. Small businesses struggle to compete with multinational corporations. I believe we should embrace the benefits of globalization while preserving our local identity and traditions.`,
    `Artificial intelligence is rapidly changing our world. AI can analyze massive amounts of data, recognize patterns, and even create art. Self-driving cars, virtual assistants, and medical diagnosis systems are just a few examples. While AI brings incredible opportunities, it also raises ethical questions. Will AI replace human jobs? How do we ensure AI systems are fair? I think AI should be developed carefully with human values in mind. The goal should be to augment human abilities, not replace them.`,
    `Mental health is just as important as physical health, yet it is often overlooked. Stress, anxiety, and depression affect millions of people worldwide. Many people suffer in silence because of stigma. They are afraid to ask for help. I believe we should talk openly about mental health. Schools should provide counseling services. Exercise, meditation, and talking to trusted people can help manage stress. Taking care of your mind is not a sign of weakness. It is a sign of strength.`,
    `Space exploration has always fascinated humanity. From the first moon landing to Mars rovers, we have achieved incredible things. Space programs have given us technologies like GPS and satellite communications. Recently, private companies like SpaceX have made space travel more accessible. However, some people argue that we should solve problems on Earth before exploring space. I believe both are possible. Investing in space science leads to innovations that benefit everyone on Earth.`,
    `Fossil fuels have powered our world for centuries, but they come at a great cost to the environment. Renewable energy sources like solar, wind, and hydroelectric power offer a cleaner alternative. Solar panels convert sunlight into electricity. Wind turbines harness the power of the wind. Many countries are investing heavily in renewable energy. The transition to clean energy is not only good for the planet but also creates new jobs. I hope to see a world powered entirely by renewable energy in my lifetime.`,
    `Cultural diversity makes our world rich and interesting. Every culture has unique traditions, food, music, and values. Living in a diverse society exposes us to different perspectives. It teaches us tolerance and broadens our understanding. Unfortunately, discrimination still exists in many forms. People are judged because of their race, religion, or background. I believe that schools should teach about different cultures and promote respect for everyone. Celebrating diversity makes communities stronger and more vibrant.`,
    `The gig economy is changing how people work. Instead of traditional full-time jobs, many people now work as freelancers or independent contractors. Platforms like Uber, Fiverr, and Upwork connect workers with clients. This offers flexibility and freedom. People can work from anywhere and choose their hours. However, gig work also has downsides. There is no job security, paid leave, or health insurance. Workers must manage their own finances and taxes. I think the gig economy is a double-edged sword.`,
    `In the age of information, media literacy is an essential skill. We are bombarded with news, advertisements, and content from countless sources. Not everything we see online is true. Some content is misleading or deliberately false. Media literacy means being able to analyze and evaluate information critically. We should check the source, look for evidence, and consider different viewpoints. Teaching media literacy in schools should be a priority. It empowers people to make informed decisions.`,
    `Sustainable living means making choices that reduce our environmental impact. This includes reducing waste, conserving energy, and choosing eco-friendly products. I started my journey toward sustainability by making small changes. I carry a reusable shopping bag and avoid single-use plastics. I compost food waste and buy second-hand clothes. These changes may seem small, but they add up. If millions of people adopt sustainable habits, we can significantly reduce pollution and conserve resources for future generations.`,
    `Is a university degree necessary for success? This question has sparked debate. On one hand, a degree opens doors to many careers and typically leads to higher earnings. University also develops critical thinking and networking skills. On the other hand, many successful entrepreneurs never completed university. The rise of online courses and vocational training provides alternative paths. I believe the answer depends on the individual and their goals. Higher education is valuable, but it is not the only path to success.`
  ],
  C1: [
    `Psychologist Barry Schwartz argues that while some choice is undoubtedly better than none, an abundance of choices can lead to anxiety and paralysis. In modern societies, we face countless options in every aspect of life. From career paths to consumer goods, the sheer volume of possibilities can be overwhelming. This phenomenon, known as the paradox of choice, suggests that beyond a certain threshold, additional options diminish our satisfaction. The key is learning to be satisfied with "good enough" rather than constantly seeking the best.`,
    `Understanding how the brain learns can dramatically improve our study methods. Neuroplasticity, the brain's ability to reorganize itself, is the foundation of all learning. When we learn something new, our neurons form connections called synapses. Repeated activation strengthens these connections through a process called long-term potentiation. This explains why spaced repetition is more effective than cramming. By reviewing information at increasing intervals, we signal to our brains that this information is important and worth retaining. Sleep also plays a crucial role in memory consolidation.`,
    `Cryptocurrency has emerged as a revolutionary force in the financial world. Bitcoin, created in 2009 by the pseudonymous Satoshi Nakamoto, introduced the concept of decentralized digital currency. The underlying blockchain technology enables secure, transparent transactions without intermediaries like banks. Proponents argue that cryptocurrency democratizes finance. Critics point to extreme volatility, energy consumption, and use in illegal activities. Regulatory frameworks are still evolving. The long-term viability of cryptocurrency remains uncertain, but its impact on how we think about money is undeniable.`,
    `CRISPR-Cas9 technology has made gene editing precise, affordable, and accessible. This breakthrough raises profound ethical questions. Should we edit human embryos to eliminate genetic diseases? What about enhancing traits like intelligence or athletic ability? The distinction between therapy and enhancement becomes blurred. There are concerns about creating genetic inequality between those who can afford enhancements and those who cannot. Many scientists advocate for a moratorium on heritable editing until society reaches consensus. The power to rewrite the code of life demands careful ethical consideration.`,
    `Social media platforms are designed to be addictive. They exploit psychological principles like variable reward schedules, social validation, and fear of missing out. Every notification triggers a small dopamine release in our brains, creating a feedback loop that keeps us scrolling. The endless feed is engineered to maximize engagement, not user well-being. Studies have linked excessive social media use to increased rates of anxiety, depression, and loneliness. Digital literacy and mindful usage are essential for maintaining healthy relationships with technology.`,
    `The workplace is undergoing a profound transformation. Remote work, once a niche arrangement, has become mainstream. Automation and AI are reshaping industries, eliminating some jobs while creating others. The skills required for success are shifting. Creativity, emotional intelligence, and adaptability are increasingly valued over routine technical skills. Lifelong learning is no longer optional. Companies are experimenting with four-day work weeks and flexible schedules. The traditional career ladder is being replaced by a lattice of diverse experiences.`,
    `Every purchase we make is a vote for the kind of world we want to live in. Conscious consumerism is the practice of making buying decisions based on ethical and environmental considerations. This includes choosing fair trade products, supporting local businesses, avoiding companies with poor labor practices, and reducing consumption altogether. Fast fashion produces enormous waste and exploits workers. By choosing sustainable brands and buying less, consumers can drive change. However, critics argue that systemic change requires government regulation too.`,
    `Negotiation is an essential skill in both professional and personal life. Effective negotiation is not about winning at the expense of the other party. The most successful negotiators aim for win-win outcomes. Preparation is crucial: understand your goals, know your alternatives, and research the other side's interests. Active listening is more powerful than aggressive speaking. Asking open-ended questions reveals what the other party truly values. Emotional intelligence allows you to read the room and adjust your approach. The best negotiators create value rather than simply claiming it.`,
    `Cities are responsible for over 70% of global carbon emissions. As urban populations grow, sustainable city design becomes critical. Green architecture incorporates energy-efficient systems, green roofs, and sustainable materials. Smart city technologies use data to optimize traffic, waste management, and energy use. Public transportation reduces individual car usage. Pedestrian-friendly design encourages walking and cycling. Sustainable cities are not just environmentally friendly; they are also more livable and equitable.`,
    `Positive psychology, pioneered by Martin Seligman, studies what makes life worth living. Research reveals that happiness is not primarily determined by external circumstances. Genetics account for about 50% of our happiness set point. Life circumstances surprisingly only about 10%. The remaining 40% is determined by intentional activities. Practices like gratitude journaling, acts of kindness, meditation, and nurturing social connections significantly boost well-being. The pursuit of meaning and engagement matters more than the pursuit of pleasure.`
  ],
  C2: [
    `Epistemology, the branch of philosophy concerned with the nature and scope of knowledge, has acquired unprecedented relevance in the digital era. The democratization of information through the internet has paradoxically made it more difficult to ascertain truth. Misinformation, disinformation, and deepfakes challenge our traditional criteria for justification. The classical tripartite definition of knowledge as justified true belief seems inadequate when entire realities can be simulated. We are witnessing an epistemic crisis where authority is fragmented and trust in institutions has eroded.`,
    `Quantum computing represents a paradigm shift in computational capability. Unlike classical bits which represent either 0 or 1, quantum bits or qubits exploit superposition to exist in multiple states simultaneously. Entanglement allows qubits to be correlated in ways that classical physics cannot explain. This enables quantum computers to solve certain problems exponentially faster than classical computers. Applications include drug discovery, climate modeling, and cryptography. However, qubits are extremely sensitive to environmental noise and require near absolute zero temperatures.`,
    `Time is simultaneously one of the most familiar and most mysterious aspects of human experience. Physicists describe time as a dimension intertwined with space, yet our subjective experience of time differs dramatically from its physical description. Phenomenologists like Husserl and Heidegger distinguished between objective clock time and lived time. Memory and anticipation structure our temporal experience. The present moment is not a dimensionless point but a duration that contains traces of the past and expectations of the future. This phenomenal time gives narrative structure to our lives.`,
    `Energy has always been central to geopolitical power dynamics. The discovery of oil reshaped the 20th century, creating both wealth and conflict. Today, the global energy transition toward renewables is redrawing the geopolitical map. Traditional oil-producing nations face an existential challenge as demand for fossil fuels may peak within decades. Countries with abundant solar and wind resources, or with access to critical minerals like lithium and cobalt for batteries, are gaining strategic importance. The shift to clean energy is fundamentally reshaping international relations and global power structures.`,
    `The hard problem of consciousness, termed by philosopher David Chalmers, asks why and how physical processes in the brain give rise to subjective experience. While neuroscience has made remarkable progress in identifying neural correlates of consciousness, the explanatory gap remains. How does matter become aware of itself? Integrated information theory proposes that consciousness corresponds to a system's capacity for information integration. Despite advances, consciousness remains perhaps the deepest scientific mystery.`,
    `Existentialism, a philosophical movement associated with Sartre, Camus, and Kierkegaard, emphasizes individual freedom, choice, and responsibility. The central tenet is that existence precedes essence: we are not born with a predetermined purpose but must create our own meaning. In an age of uncertainty, existentialist ideas have renewed relevance. We face the anxiety of freedom and the responsibility of authentic living. The challenge is to embrace our freedom without being paralyzed by it, and to find meaning in a universe that offers no guarantees.`,
    `We live in a post-truth era where objective facts are less influential in shaping public opinion than appeals to emotion and personal belief. The proliferation of echo chambers and algorithmic content curation reinforces existing beliefs and creates polarized realities. Critical thinking alone is insufficient; we need epistemic humility and a willingness to engage with perspectives different from our own. Rebuilding a shared foundation of truth requires both systemic changes to information ecosystems and individual commitment to intellectual honesty.`,
    `Economic inequality has reached levels not seen in a century. The gap between the wealthiest and the rest of society continues to widen. Factors include technological change that rewards highly skilled workers, globalization that disadvantages certain industries, and tax policies that favor capital over labor. The concentration of wealth has implications for democracy, social cohesion, and economic mobility. Addressing inequality requires thoughtful policy interventions including progressive taxation, investment in education, and strengthening social safety nets.`,
    `Artificial General Intelligence (AGI) refers to AI systems that match or exceed human cognitive capabilities across virtually all domains. While current AI excels at narrow tasks, AGI remains theoretical. Its potential arrival raises profound questions. Would AGI help solve humanity's greatest challenges or pose existential risks? How would society adapt to machines that can perform any intellectual task? The alignment problem ensuring that AGI goals align with human values is perhaps the most important technical challenge of our time.`,
    `The question of life's meaning has occupied philosophers, theologians, and thinkers for millennia. Modern perspectives offer diverse answers. Existentialists argue that meaning is self-created. Religious traditions locate meaning in relationship with the divine. Positive psychology suggests that meaning arises from belonging, purpose, and contribution. Perhaps meaning is not something we discover but something we construct through our choices, relationships, and commitments. The search for meaning may itself be what makes life meaningful.`
  ]
};

const VOCAB = {
  A1: [
    [{w:'wake up',m:'يستيقظ',p:'weɪk ʌp',e:'I wake up at 7.'},{w:'breakfast',m:'فطور',p:'ˈbrekfəst',e:'I eat breakfast.'},{w:'usually',m:'عادةً',p:'ˈjuːʒuəli',e:'I usually drink milk.'},{w:'homework',m:'واجب',p:'ˈhoʊmwɜːrk',e:'I do homework.'},{w:'dinner',m:'عشاء',p:'ˈdɪnər',e:'We eat dinner.'}],
    [{w:'father',m:'أب',p:'ˈfɑːðər',e:'My father is a doctor.'},{w:'mother',m:'أم',p:'ˈmʌðər',e:'My mother is kind.'},{w:'grandparents',m:'أجداد',p:'ˈɡrænpeərənts',e:'I visit my grandparents.'},{w:'weekend',m:'عطلة نهاية الأسبوع',p:'ˌwiːkˈend',e:'We go out on weekends.'},{w:'together',m:'معاً',p:'təˈɡeðər',e:'We eat together.'}],
    [{w:'favorite',m:'مفضل',p:'ˈfeɪvərɪt',e:'Pizza is my favorite.'},{w:'delicious',m:'لذيذ',p:'dɪˈlɪʃəs',e:'The food is delicious.'},{w:'kitchen',m:'مطبخ',p:'ˈkɪtʃɪn',e:'I help in the kitchen.'},{w:'sometimes',m:'أحياناً',p:'ˈsʌmtaɪmz',e:'I sometimes cook.'},{w:'bitter',m:'مر',p:'ˈbɪtər',e:'Coffee is bitter.'}],
    [{w:'living room',m:'غرفة المعيشة',p:'ˈlɪvɪŋ ruːm',e:'We watch TV there.'},{w:'bedroom',m:'غرفة نوم',p:'ˈbedruːm',e:'My bedroom is blue.'},{w:'garden',m:'حديقة',p:'ˈɡɑːrdn',e:'There is a garden.'},{w:'in front of',m:'أمام',p:'ɪn frʌnt ʌv',e:'In front of the house.'},{w:'between',m:'بين',p:'bɪˈtwiːn',e:'Between the houses.'}],
    [{w:'supermarket',m:'سوبر ماركت',p:'ˈsuːpərmɑːrkɪt',e:'We go to the supermarket.'},{w:'cashier',m:'كاشير',p:'kæˈʃɪr',e:'Pays at the cashier.'},{w:'busy',m:'مزدحم',p:'ˈbɪzi',e:'It is busy.'},{w:'carry',m:'يحمل',p:'ˈkæri',e:'I carry the bags.'},{w:'buy',m:'يشتري',p:'baɪ',e:'We buy milk.'}],
    [{w:'pet',m:'حيوان أليف',p:'pet',e:'I have a pet.'},{w:'tail',m:'ذيل',p:'teɪl',e:'The dog has a tail.'},{w:'throw',m:'يرمي',p:'θroʊ',e:'I throw the ball.'},{w:'best friend',m:'أفضل صديق',p:'best frend',e:'He is my best friend.'},{w:'sleep',m:'ينام',p:'sliːp',e:'The dog sleeps.'}],
    [{w:'sunny',m:'مشمس',p:'ˈsʌni',e:'Today is sunny.'},{w:'weather',m:'طقس',p:'ˈweðər',e:'The weather is nice.'},{w:'summer',m:'صيف',p:'ˈsʌmər',e:'Summer is hot.'},{w:'winter',m:'شتاء',p:'ˈwɪntər',e:'Winter is cold.'},{w:'spring',m:'ربيع',p:'sprɪŋ',e:'Spring is beautiful.'}],
    [{w:'subject',m:'مادة',p:'ˈsʌbdʒɪkt',e:'I study subjects.'},{w:'teacher',m:'معلم',p:'ˈtiːtʃər',e:'My teacher is nice.'},{w:'break time',m:'استراحة',p:'breɪk taɪm',e:'We play at break.'},{w:'finish',m:'ينتهي',p:'ˈfɪnɪʃ',e:'School finishes at 2.'},{w:'learn',m:'يتعلم',p:'lɜːrn',e:'I learn new words.'}],
    [{w:'hobby',m:'هواية',p:'ˈhɑːbi',e:'Drawing is my hobby.'},{w:'draw',m:'يرسم',p:'drɔː',e:'I like to draw.'},{w:'ride a bike',m:'يركب دراجة',p:'raɪd ə baɪk',e:'I ride my bike.'},{w:'cartoon',m:'رسوم متحركة',p:'kɑːrˈtuːn',e:'I watch cartoons.'},{w:'free time',m:'وقت فراغ',p:'friː taɪm',e:'In my free time.'}],
    [{w:'shirt',m:'قميص',p:'ʃɜːrt',e:'I wear a shirt.'},{w:'pants',m:'بنطلون',p:'pænts',e:'I wear pants.'},{w:'comfortable',m:'مريح',p:'ˈkʌmfərtəbl',e:'Comfortable clothes.'},{w:'sweater',m:'سترة',p:'ˈswetər',e:'I wear a sweater.'},{w:'mall',m:'مول',p:'mɔːl',e:'We go to the mall.'}]
  ],
  A2: [
    [{w:'beach',m:'شاطئ',p:'biːtʃ',e:'We went to the beach.'},{w:'sandcastle',m:'قلعة رملية',p:'ˈsændkæsl',e:'I built a sandcastle.'},{w:'umbrella',m:'مظلة',p:'ʌmˈbrelə',e:'We took an umbrella.'},{w:'sunset',m:'غروب',p:'ˈsʌnset',e:'We watched the sunset.'},{w:'photo',m:'صورة',p:'ˈfoʊtoʊ',e:'We took photos.'}],
    [{w:'friend',m:'صديق',p:'frend',e:'He is my friend.'},{w:'funny',m:'مضحك',p:'ˈfʌni',e:'He is funny.'},{w:'helpful',m:'مساعد',p:'ˈhelpfl',e:'He is helpful.'},{w:'laugh',m:'يضحك',p:'læf',e:'He makes me laugh.'},{w:'lucky',m:'محظوظ',p:'ˈlʌki',e:'I am lucky.'}],
    [{w:'headache',m:'صداع',p:'ˈhedeɪk',e:'I have a headache.'},{w:'fever',m:'حمى',p:'ˈfiːvər',e:'I have a fever.'},{w:'temperature',m:'درجة حرارة',p:'ˈtemprətʃər',e:'Checked my temperature.'},{w:'medicine',m:'دواء',p:'ˈmedɪsn',e:'He gave me medicine.'},{w:'rest',m:'راحة',p:'rest',e:'The doctor said rest.'}],
    [{w:'market',m:'سوق',p:'ˈmɑːrkɪt',e:'There is a market.'},{w:'library',m:'مكتبة',p:'ˈlaɪbreri',e:'I go to the library.'},{w:'lake',m:'بحيرة',p:'leɪk',e:'There is a lake.'},{w:'restaurant',m:'مطعم',p:'ˈrestərɑːnt',e:'Many restaurants.'},{w:'center',m:'مركز',p:'ˈsentər',e:'The city center.'}],
    [{w:'birthday',m:'عيد ميلاد',p:'ˈbɜːrθdeɪ',e:'My birthday.'},{w:'balloon',m:'بالون',p:'bəˈluːn',e:'We had balloons.'},{w:'candle',m:'شمعة',p:'ˈkændl',e:'I blew out candles.'},{w:'decorate',m:'يزين',p:'ˈdekəreɪt',e:'We decorated.'},{w:'wish',m:'أمنية',p:'wɪʃ',e:'I made a wish.'}],
    [{w:'secret',m:'سر',p:'ˈsiːkrət',e:'A secret garden.'},{w:'garden',m:'حديقة',p:'ˈɡɑːrdn',e:'The garden is old.'},{w:'plant',m:'يزرع',p:'plænt',e:'She plants flowers.'},{w:'nature',m:'طبيعة',p:'ˈneɪtʃər',e:'About nature.'},{w:'adventure',m:'مغامرة',p:'ədˈventʃər',e:'Adventure stories.'}],
    [{w:'boil',m:'يغلي',p:'bɔɪl',e:'We boiled water.'},{w:'sauce',m:'صلصة',p:'sɔːs',e:'Tomato sauce.'},{w:'stir',m:'يقلب',p:'stɜːr',e:'I stirred the sauce.'},{w:'smell',m:'رائحة',p:'smel',e:'It smelled good.'},{w:'proud',m:'فخور',p:'praʊd',e:'I felt proud.'}],
    [{w:'pen pal',m:'صديق مراسلة',p:'pen pæl',e:'I write to my pen pal.'},{w:'language',m:'لغة',p:'ˈlæŋɡwɪdʒ',e:'Learn languages.'},{w:'letter',m:'رسالة',p:'ˈletər',e:'I wrote a letter.'},{w:'country',m:'بلد',p:'ˈkʌntri',e:'Your country.'},{w:'wish',m:'تمنيات',p:'wɪʃ',e:'Best wishes.'}],
    [{w:'kitten',m:'قطة صغيرة',p:'ˈkɪtn',e:'I found a kitten.'},{w:'scared',m:'خائف',p:'skerd',e:'It looked scared.'},{w:'hungry',m:'جائع',p:'ˈhʌŋɡri',e:'The kitten was hungry.'},{w:'towel',m:'منشفة',p:'ˈtaʊəl',e:'A soft towel.'},{w:'take care of',m:'يعتني بـ',p:'teɪk ker ʌv',e:'I take care of her.'}],
    [{w:'dream',m:'حلم',p:'driːm',e:'My dream job.'},{w:'teacher',m:'معلم',p:'ˈtiːtʃər',e:'I want to be a teacher.'},{w:'culture',m:'ثقافة',p:'ˈkʌltʃər',e:'Other cultures.'},{w:'travel',m:'يسافر',p:'ˈtrævl',e:'I want to travel.'},{w:'activity',m:'نشاط',p:'ækˈtɪvɪti',e:'Fun activities.'}]
  ]
};

const QUESTIONS = {
  A1: [
    [{q:'What time do I wake up?',o:['6:00','7:00','8:00','9:00'],a:1},{q:'What do I eat for breakfast?',o:['Rice','Bread and milk','Eggs','Fruit'],a:1},{q:'Where do I go after breakfast?',o:['Park','School','Market','Library'],a:1},{q:'What do I do in the afternoon?',o:['Watch TV','Play outside','Do homework','Sleep'],a:2},{q:'What time do I go to bed?',o:['9 pm','10 pm','11 pm','12 am'],a:1}],
    [{q:'What does my father do?',o:['Teacher','Doctor','Engineer','Farmer'],a:1},{q:'How many siblings do I have?',o:['One','Two','Three','None'],a:1},{q:'How old is my brother?',o:['8','10','12','15'],a:1},{q:'Where do we go on weekends?',o:['Park','Grandparents','Beach','Mall'],a:1},{q:'What does grandmother make?',o:['Bread','Cake','Juice','Salad'],a:1}],
    [{q:'What is my favorite food?',o:['Pasta','Pizza','Rice','Salad'],a:1},{q:'What is on the pizza?',o:['Chicken','Cheese and tomatoes','Meat','Fish'],a:1},{q:'What do I eat for breakfast?',o:['Pizza','Cereal with milk','Pasta','Rice'],a:1},{q:'Why don\'t I like coffee?',o:['Hot','Bitter','Sweet','Cold'],a:1},{q:'Where do I help my mother?',o:['Garden','Kitchen','Living room','Bathroom'],a:1}],
    [{q:'How many rooms in my house?',o:['3','4','5','6'],a:1},{q:'What color is my bedroom?',o:['Green','Blue','Red','Yellow'],a:1},{q:'What do we do in the living room?',o:['Cook','Watch TV','Sleep','Shower'],a:1},{q:'Where is the kitchen?',o:['Next to living room','Next to bedroom','Upstairs','Outside'],a:0},{q:'What is in front of the house?',o:['Pool','Garden','Shop','School'],a:1}],
    [{q:'Where do I go with my mother?',o:['Park','School','Supermarket','Library'],a:2},{q:'Which fruit do we NOT buy?',o:['Apples','Bananas','Grapes','Oranges'],a:2},{q:'Who pays at the cashier?',o:['Me','My mother','My father','Sister'],a:1},{q:'How does the supermarket feel?',o:['Quiet','Big and busy','Small','Empty'],a:1},{q:'Why am I happy?',o:['Got a toy','We have food','Saw a friend','Went to park'],a:1}],
    [{q:'What is my pet?',o:['Cat','Dog','Bird','Fish'],a:1},{q:'What color is Max?',o:['Black','Brown and white','White','Golden'],a:1},{q:'How old is Max?',o:['1 year','2 years','3 years','4 years'],a:1},{q:'Where does Max play?',o:['Inside','In the garden','In the park','On street'],a:1},{q:'Where does Max sleep?',o:['Sofa','In his bed','My bed','Outside'],a:1}],
    [{q:'How is the weather today?',o:['Rainy','Sunny','Cloudy','Snowy'],a:1},{q:'What do I wear today?',o:['Jacket','T-shirt and shorts','Coat','Sweater'],a:1},{q:'Where do we go in summer?',o:['Park','Beach','Mountain','Library'],a:1},{q:'What do I wear in winter?',o:['T-shirt','Dress','Jacket and hat','Shorts'],a:2},{q:'Why do I like spring?',o:['Hot','Flowers are beautiful','Snows','Leaves fall'],a:1}],
    [{q:'When do I go to school?',o:['Sat-Wed','Sun-Thu','Mon-Fri','Sun-Wed'],a:1},{q:'What time does school start?',o:['7 am','8 am','9 am','10 am'],a:1},{q:'Which subjects do I like?',o:['Math & Art','English & Science','History & Geo','PE & Music'],a:1},{q:'What do I do at break?',o:['Study','Play and eat snacks','Sleep','Read'],a:1},{q:'How do I go home?',o:['Walk','Bus','Car','Bike'],a:1}],
    [{q:'What do I like to draw?',o:['Cars','Animals and flowers','People','Food'],a:1},{q:'What is my book about?',o:['A magic tree','A lost dog','A knight','Space'],a:0},{q:'When do I read?',o:['Morning','Before sleep','Lunch','After school'],a:1},{q:'Where do I ride my bike?',o:['Street','Park','School','Garden'],a:1},{q:'Which sport do I play?',o:['Basketball','Football','Tennis','Swimming'],a:1}],
    [{q:'What color shirt am I wearing?',o:['Red','Blue','Green','White'],a:1},{q:'Where does mom buy clothes?',o:['Supermarket','Mall','Library','School'],a:1},{q:'What do I wear in winter?',o:['Shorts','T-shirts','Sweaters and jackets','Sandals'],a:2},{q:'What is my favorite color?',o:['Red','Blue','Green','Black'],a:1},{q:'What color are my new shoes?',o:['Blue and white','White and red','Black and white','Red and blue'],a:1}]
  ]
};

function generateVocab(level, idx) {
  if (VOCAB[level] && VOCAB[level][idx]) return VOCAB[level][idx];
  const topics = TOPICS[level];
  const topic = topics ? topics[idx] || 'General' : 'General';
  const words = topic.split(' ').filter(w => w.length > 4).slice(0, 5);
  return words.map(w => {
    const lower = w.toLowerCase();
    return { w, m: `معنى ${lower}`, p: `/${lower}/`, e: `"${w}" is an important word in this lesson.` };
  });
}

function generateQuestions(level, idx, story) {
  if (QUESTIONS[level] && QUESTIONS[level][idx]) return QUESTIONS[level][idx];
  const sentences = story.split(/[.!?]+/).filter(s => s.trim().split(' ').length > 5);
  return sentences.slice(0, 5).map((s, i) => {
    const words = s.trim().split(' ');
    const keyWord = words.find(w => w.length > 4) || words[0] || 'topic';
    const cleanW = keyWord.replace(/[^a-zA-Z]/g, '');
    return {
      q: `What does the story say about "${cleanW || 'the topic'}"?`,
      o: [`It mentions that ${cleanW} is important`, `The story does not mention this`, `It describes ${cleanW} in detail`, `It says ${cleanW} is the main idea`],
      a: 0
    };
  });
}

function getLessonData(levelId, lessonIndex) {
  const idx = lessonIndex;
  const level = LEVELS.find(l => l.id === levelId);
  if (!level) return null;
  const topics = TOPICS[levelId];
  const stories = STORIES[levelId];
  if (!topics || !stories) return null;
  const topic = topics[idx] || 'General Topic';
  const story = stories[idx] || 'Story content not available. Please use AI generation.';
  let vocab = generateVocab(levelId, idx);
  let questions = generateQuestions(levelId, idx, story);
  
  const conversationPrompts = [
    `What do you think about the topic: "${topic}"? Share your thoughts.`,
    `How does this topic relate to your own experience?`,
    `What new vocabulary did you learn from this lesson?`
  ];
  
  return { id: `${levelId}-${idx+1}`, title: topic, topic, story, vocab, questions, chatPrompt: conversationPrompts[0], conversationPrompts };
}
